server:
  port: 8989
  servlet:
    context-path: /wdy

logging:
  config:
    classpath: log4j2.xml

spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

